// Pixel-art renderer: every sprite/icon is a grid of square pixels (no curves).
// One global char->color palette keeps the grids compact and consistent.

export const CH: Record<string, string> = {
  K: '#3a2a1a', e: '#2a2018', W: '#fdfdf6',
  y: '#f6c343', Y: '#d79b22',
  m: '#6fd3e0', M: '#3fb6c9',
  b: '#ffd34d', B: '#e8a11f',
  g: '#5aa84a', G: '#3f8a35', l: '#7cc865',
  t: '#8a5a32', T: '#6e4626',
  r: '#a7b0ba', R: '#828c98', w: '#c8d0d8',
  s: '#f4c9a0', h: '#7a4a2a',
  S: '#e06b6b', F: '#c25151',
  p: '#4a6fa5', P: '#3a5688',
  a: '#e3c45a', A: '#c9a93f',
  o: '#e8893f', O: '#c96f28',
  f: '#e2515b',
  n: '#cf9b54', N: '#a8743c',
  E: '#f4ead2',
  c: '#e3413f', k: '#f0a23a',
  i: '#f08a2a', I: '#f6d24a',
  x: '#caa06a', X: '#a8804c',
  u: '#f0e3c8', U: '#caa56e',
  z: '#b8bcc4', Z: '#8a909a',
  d: '#e0a86a', D: '#c2864a',
  j: '#f6dcc8', J: '#d9a98a',
  v: '#d9656a', V: '#b34a50',
  Q: '#c07a4a',
  L: '#7a5536', q: '#8a6442',
}

type Anchor = 'foot' | 'center' | 'topleft'

/** Draw a pixel grid. px = size of one pixel. Rows may differ in length (padded transparent). */
export function drawGrid(
  ctx: CanvasRenderingContext2D, rows: string[], x: number, y: number, px: number,
  anchor: Anchor = 'foot', pal?: Record<string, string>,
) {
  const w = rows.reduce((m, r) => Math.max(m, r.length), 0)
  const h = rows.length
  const cx = anchor === 'topleft' ? x : x - (w * px) / 2
  const cy = anchor === 'foot' ? y - h * px : anchor === 'center' ? y - (h * px) / 2 : y
  const ox = Math.round(cx)
  const oy = Math.round(cy)
  for (let gy = 0; gy < h; gy++) {
    const row = rows[gy]
    for (let gx = 0; gx < row.length; gx++) {
      const ch = row[gx]
      if (ch === '.' || ch === ' ') continue
      const col = (pal && pal[ch]) || CH[ch]
      if (!col) continue
      ctx.fillStyle = col
      // tiny overlap so fractional camera zoom leaves no seams between pixels
      ctx.fillRect(ox + gx * px, oy + gy * px, px + 0.5, px + 0.5)
    }
  }
}

// ---- UI / object icons (square, ~9px) ----
export const ICONS: Record<string, string[]> = {
  coin: [
    '..YYYYY..',
    '.YyyyyyY.',
    'YyyyYyyyY',
    'YyyyYyyyY',
    'YyyyYyyyY',
    'YyyyYyyyY',
    'YyyyYyyyY',
    '.YyyyyyY.',
    '..YYYYY..',
  ],
  gem: [
    '..mMMm...',
    '.mmMMmm..',
    'mmmMMmmm.',
    'mmmMMmmm.',
    '.MMmMMM..',
    '..MMMM...',
    '...MM....',
    '....M....',
  ],
  bolt: [
    '....bb...',
    '...bb....',
    '..bbb....',
    '.bbbbbb..',
    '...bbb...',
    '..bbb....',
    '..bb.....',
    '.bb......',
  ],
  bag: [
    '..K...K..',
    '.K.....K.',
    '.KxxxxxK.',
    'KxxxxxxxK',
    'KxXXXXXxK',
    'KxxxXxxxK',
    'KxxxxxxxK',
    '.KKKKKKK.',
  ],
  shop: [
    'SSSSSSSSS',
    'WSWSWSWSW',
    'UUUUUUUUU',
    'UxxxxxxxU',
    'Ux.KKK.xU',
    'Ux.K.K.xU',
    'UxxKxKxxU',
    'UUUUUUUUU',
  ],
  hammer: [
    '..zzzzz..',
    '.zzzzzzz.',
    '.zzzzzzz.',
    '....t....',
    '....t....',
    '....t....',
    '....t....',
    '...TTT...',
  ],
  pot: [
    '..z...z..',
    '.zZZZZZz.',
    'zZZZZZZZz',
    '.ZzzzzzZ.',
    '.ZzzzzzZ.',
    '.ZZZZZZZ.',
    '..iIIIi..',
    '..i.i.i..',
  ],
  scroll: [
    '.UUUUUUU.',
    'UuuuuuuuU',
    'Uu.KKK.uU',
    'Uu.....uU',
    'Uu.KKK.uU',
    'Uu.....uU',
    'Uu.KK..uU',
    '.UUUUUUU.',
  ],
  book: [
    '.KKKKKKK.',
    'KuuuKuuuK',
    'KuuuKuuuK',
    'KuuuKuuuK',
    'KuuuKuuuK',
    'KuuuKuuuK',
    'KuuuKuuuK',
    '.KKKKKKK.',
  ],
  gear: [
    '...z.z...',
    '.zzzzzzz.',
    '.zzKKKzz.',
    'zzK...Kzz',
    'zzK...Kzz',
    'zzK...Kzz',
    '.zzKKKzz.',
    '.zzzzzzz.',
  ],
  chicken: [
    '...cc....',
    '..WWWk...',
    '.WWWWWk..',
    '.WeWWWW..',
    'WWWWWWW..',
    'WWWWWWW..',
    '.WW.WW...',
    '.k...k...',
  ],
  egg: [
    '...EE....',
    '..EWEE...',
    '.EWEEEE..',
    '.EEEEEE..',
    'EEEEEEEE.',
    'EEEEEEEE.',
    '.EEEEEE..',
    '..EEEE...',
  ],
  wood: [
    'ttttttttt',
    'tTtTtTtTt',
    'ttttttttt',
    '.........',
    'ttttttttt',
    'tTtTtTtTt',
    'ttttttttt',
    '.........',
  ],
  stone: [
    '...rrr...',
    '..rwwwr..',
    '.rwwwwwr.',
    'rwwwwwwwr',
    'rRRRRRRRr',
    '.RRRRRRR.',
    '..RRRRR..',
    '.........',
  ],
  fiber: [
    '....g....',
    '...glg...',
    '..g.l.g..',
    '.g..l..g.',
    'g...l...g',
    '....l....',
    '....l....',
    '....l....',
  ],
  mushroom: [
    '..vvvvv..',
    '.vVvvvVv.',
    'vvvvvvvvv',
    'vVvvvvvVv',
    '.vvvvvvv.',
    '...WWW...',
    '...WWW...',
    '...WWW...',
  ],
  shell: [
    '...jjj...',
    '..jJjJj..',
    '.jJjJjJj.',
    'jJjJjJjJj',
    'jJjJjJjJj',
    '.jjjjjjj.',
    '..jjjjj..',
    '.........',
  ],
  wheat: [
    '....a....',
    '...aAa...',
    '..aAaAa..',
    '...aAa...',
    '..aAaAa..',
    '...aAa...',
    '....t....',
    '....t....',
  ],
  carrot: [
    '..g.g.g..',
    '..ggggg..',
    '...ooo...',
    '..ooooo..',
    '..oOoOo..',
    '...ooo...',
    '...oo....',
    '....o....',
  ],
  strawberry: [
    '...gg....',
    '..gffg...',
    '.ffffff..',
    '.fWffWf..',
    '.ffWfff..',
    '..ffff...',
    '..ffff...',
    '...ff....',
  ],
  bread: [
    '.........',
    '..nnnnn..',
    '.nNnnnNn.',
    'nnnnnnnnn',
    'nnnnnnnnn',
    'nNnnnnnNn',
    '.nnnnnnn.',
    '..NNNNN..',
  ],
  pancake: [
    '...yy....',
    '..nnnnn..',
    '.nnnnnnn.',
    '.NNNNNNN.',
    '.nnnnnnn.',
    '.NNNNNNN.',
    '..nnnnn..',
    '.........',
  ],
  berry_jam: [
    '...XXX...',
    '..U...U..',
    '.UzzzzzU.',
    '.ZfffffZ.',
    '.ZfffffZ.',
    '.ZfWffZ..',
    '.ZfffffZ.',
    '.ZZZZZZZ.',
  ],
  copper_ore: [
    '...QQQ...',
    '..QwwwQ..',
    '.QwwwwwQ.',
    'QwwwwwwwQ',
    'QQQQQQQQQ',
    '.QQQQQQQ.',
    '..QQQQQ..',
    '.........',
  ],
  iron_ore: [
    '...zzz...',
    '..zwwwz..',
    '.zwwwwwz.',
    'zwwwwwwwz',
    'zZZZZZZZz',
    '.ZZZZZZZ.',
    '..ZZZZZ..',
    '.........',
  ],
  raw_gem: [
    '..mMMm...',
    '.mmMMmm..',
    'mmmMMmmm.',
    'mmmMMmmm.',
    '.MMmMMM..',
    '..MMMM...',
    '...MM....',
    '....M....',
  ],
  tent: [
    '....y....',
    '....d....',
    '...ddd...',
    '..ddddd..',
    '.dddoddd.',
    '.ddoooDd.',
    'dddoooddd',
    'ddDoooDdd',
  ],
  fire: [
    '....i....',
    '...iIi...',
    '..iIIIi..',
    '..iIIIi..',
    '.iIIIIIi.',
    '.iIWIIIi.',
    '..iiiii..',
    '.tt...tt.',
  ],
  box: [
    '.XXXXXXX.',
    'XxxxxxxxX',
    'XxXxxXxxX',
    'XxxxxxxxX',
    'XxxxxxxxX',
    'XxXxxXxxX',
    'XxxxxxxxX',
    '.XXXXXXX.',
  ],
  sign: [
    '.UUUUUUU.',
    'UuaaaaauU',
    'UuaAaAauU',
    'UuaaaaauU',
    '.UUUUUUU.',
    '....t....',
    '....t....',
    '...TTT...',
  ],
  pickaxe: [
    'z.......z',
    '.zz...zz.',
    '..zz.zz..',
    '...ztz...',
    '....t....',
    '....t....',
    '....t....',
    '....T....',
  ],
  sun: [
    '..b.b.b..',
    '...bbb...',
    '.bbIIIbb.',
    'b.IIIII.b',
    '.bbIIIbb.',
    '...bbb...',
    '..b.b.b..',
    '.........',
  ],
  check: [
    '.........',
    '.......g.',
    '......gg.',
    'g....gg..',
    'gg..gg...',
    '.gggg....',
    '..gg.....',
    '...g.....',
  ],
  lock: [
    '..KKKK...',
    '.K....K..',
    '.K....K..',
    'KKKKKKKK.',
    'KyyyyyyK.',
    'KyyKKyyK.',
    'KyyKKyyK.',
    'KKKKKKKK.',
  ],
  soil: [
    'LqLqLqLqL',
    'LLLLLLLLL',
    'qLqLqLqLq',
    'LLLLLLLLL',
    'LqLqLqLqL',
    'LLLLLLLLL',
    'qLqLqLqLq',
    'LLLLLLLLL',
  ],
  sleep: [
    '.........',
    'WWWW.....',
    '..W......',
    '.W..WWW..',
    'WWW..W...',
    '....W..WW',
    '...WWW.W.',
    '......W..',
    '.....WWW.',
  ],
}

/** Render an icon to its own offscreen canvas (for crisp UI use). */
export function iconDataURL(name: string, size = 32): string {
  const rows = ICONS[name]
  if (!rows) return ''
  const c = document.createElement('canvas')
  c.width = size; c.height = size
  const ctx = c.getContext('2d')!
  const w = rows.reduce((m, r) => Math.max(m, r.length), 0)
  const px = Math.max(1, Math.floor(size / Math.max(w, rows.length)))
  const gw = w * px, gh = rows.length * px
  drawGrid(ctx, rows, (size - gw) / 2, (size - gh) / 2, px, 'topleft')
  return c.toDataURL()
}
